name: Fetch Sentiment Data

on:
  schedule:
    # Uruchamianie 2 razy dziennie (6:00 i 18:00 UTC)
    - cron: '0 6,18 * * *'
  workflow_dispatch:

jobs:
  fetch-sentiment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch Sentiment data
        run: |
          cd scripts
          python fetch_sentiment.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/sentiment/
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "😱 Update Sentiment data [automated]" && git push)
