name: Fetch Flow Data

on:
  schedule:
    # Uruchamianie co 30 minut
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  fetch-flows:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch Flow data
        run: |
          cd scripts
          python fetch_flows.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/flows/
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "💸 Update Flow data [automated]" && git push)
